@startuml
'https://plantuml.com/sequence-diagram

actor agente
agente --> (evaluar solicitud credito)
(evaluar solicitud credito)  <.. (solicitar informacion adicional al cliente) : extend si ingresos  < 1000

@enduml