@startuml
'https://plantuml.com/sequence-diagram

actor empleado

empleado -- (alta cliente)
empleado -- (introducir pedido)
empleado -- (obtener estado pedido)
empleado -- (buscar pedido)
empleado -- (cancelar pedido)

(alta cliente) .> (introducir pedido) : extends
(introducir pedido) .> (buscar cliente) : incluye
(introducir pedido) <. (pago con tarjeta) : extiende
(introducir pedido) <. (pago en cuenta) : extiende

(obtener estado pedido) .> (buscar pedido) : incluye
(cancelar pedido) .> (buscar pedido) : incluye

@enduml